### PR TITLE
Update Chinese.yml

### PR DESCRIPTION
**Pull request by ItsDApples**
Hey, I've noticed that some of the translations here might not be accurate, so I've made some corrections. Thanks for creating such an useful plugin.

Btw, may I port it to Minebbs? (It is the largest Minecraft forum in China) This can help more people learn about this useful plugin. I will not upload any files related to the plugin and will mark the relevant links and information.:)

### CODE REVIEW

**Comment by Revivalo** [comment]
Hello, thanks for the edits.
You have the permission to share the plugin on Minebbs.

**Comment by ItsDApples** [comment]
Thanks

**Comment by ItsDApples** [comment]
This is the post https://www.minebbs.com/resources/rewards-system.9385/
it may upload by a bit minutes
Thanks for this plugin

**Comment by Revivalo** [comment]
> This is the post https://www.minebbs.com/resources/rewards-system.9385/ it may upload by a bit minutes Thanks for this plugin


Missing the upgrade button.

**Pull request merged**
